#define TRUE 1
#define FALSE 0

//#define WINDOW_WIDTH 800
//#define WINDOW_HEIGHT 600
#define FONT_SIZE 28
#define NUM_MENU_ITEMS 3
#define NUM_PAUSE_ITEMS 4
#define FPS 120
#define FRAME_TARGET_TIME (1000 / FPS)
#define MAXIMUM_DISTANCE 500